version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "80:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/invoicing-app
