version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - ./data:/data/db

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "80:3000"
    env_file:
      - .env
    volumes:
      - /node_modules
    